#!/bin/bash

java -Xmx1024m -classpath "bin/:lib/weka.jar:lib/snowball.jar"  weka.classifiers.functions.SMO  -C 1.0 -L 0.0010 -P 1.0E-12 -N 0 -V 10 -W 1 -K "weka.classifiers.functions.supportVector.PolyKernel -C 250007 -E 1.0" -t arff/$1 -i
